version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: notification_postgres
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    container_name: notification_redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: notification_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0 # Используем версию, стабильно работающую со Zookeeper
    container_name: notification_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Добавляем обязательные параметры для корректного маппинга протоколов
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT